package dev.mago.android.installation

enum class InstallationStage {
    NOT_STARTED,
    CHECKING_DEVICE,
    TERMUX_REQUIRED,
    TERMUX_INITIALIZATION_REQUIRED,
    PERMISSION_REQUIRED,
    DEPLOYING_BRIDGE,
    UPDATING_PACKAGES,
    INSTALLING_DEPENDENCIES,
    INSTALLING_METASPLOIT,
    INITIALIZING_DATABASE,
    CONFIGURING_RPC,
    STARTING_SERVICES,
    VERIFYING,
    READY,
}

enum class InstallationFailureKind {
    WAITING_FOR_USER,
    RECOVERABLE_ERROR,
    STORAGE_INSUFFICIENT,
    NETWORK_UNAVAILABLE,
    TERMUX_UNAVAILABLE,
    PACKAGE_CONFLICT,
    DATABASE_ERROR,
    RPC_ERROR,
    FATAL_ERROR,
}
